"""initial

Rebased single migration: collapses the pre-embedding-v2 alembic chain
(0001-0023) into one initial migration at the embedding-v2 schema state
(chunks.embedding vector(768), schema_metadata sentinel table).

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-20
"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("key_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("permission_tier", sa.Text(), server_default="full", nullable=False),
        sa.Column("tool_overrides", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("scope_topic_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scope_folder_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("max_snippet_chars", sa.Integer(), nullable=True),
        sa.Column("rate_limit_rpm", sa.Integer(), nullable=True),
        sa.Column("rate_limit_rph", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("key_id"),
    )
    op.create_table(
        "corpus_topics",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("doc_count", sa.Integer(), nullable=False),
        sa.Column("representative_doc_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("topic_id"),
    )
    op.create_table(
        "corpus_topics_meta",
        sa.Column("id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("last_computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("corpus_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mail_accounts",
        sa.Column("account_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("imap_host", sa.Text(), nullable=False),
        sa.Column("imap_port", sa.Integer(), server_default="993", nullable=False),
        sa.Column("imap_username", sa.Text(), nullable=False),
        sa.Column("app_password_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("key_fingerprint", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("imap_host", "imap_username", name="uq_mail_accounts_host_username"),
    )
    op.create_table(
        "model_settings",
        sa.Column("model_id", sa.String(length=50), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_table(
        "oauth_clients",
        sa.Column("client_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("client_secret_hash", sa.Text(), nullable=True),
        sa.Column("client_name", sa.Text(), nullable=True),
        sa.Column("redirect_uris", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grant_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scope", sa.Text(), server_default="mcp", nullable=False),
        sa.Column("client_uri", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "schema_metadata",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("set_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("admin", "user", name="user_role"), server_default="user", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "watched_folders",
        sa.Column("folder_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("bookmark_data", sa.LargeBinary(), nullable=True),
        sa.Column("recursive", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_event_id", sa.BigInteger(), nullable=True),
        sa.Column("last_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unavailable_reason", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("auto_discovered", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("folder_id"),
    )
    op.create_table(
        "api_request_log",
        sa.Column("request_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("api_key_id", sa.UUID(), nullable=True),
        sa.Column("request_type", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("result_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duration_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.key_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("api_key_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=True),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.key_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "conversations",
        sa.Column("conversation_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), server_default="New conversation", nullable=False),
        sa.Column("mode", sa.String(length=10), server_default="chat", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_table(
        "documents",
        sa.Column("doc_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("canonical_filename", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.LargeBinary(), nullable=False),
        sa.Column(
            "pipeline_status",
            sa.Enum(
                "queued",
                "extracting",
                "extracted",
                "ocr_running",
                "ocr_done",
                "chunking",
                "chunked",
                "extracting_entities",
                "entities_done",
                "embedding",
                "embedded",
                "summarizing",
                "summarized",
                "finalizing",
                "ready",
                "error",
                name="pipeline_status",
            ),
            nullable=False,
        ),
        sa.Column("pipeline_seq", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_model", sa.Text(), nullable=True),
        sa.Column("doc_type", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("has_text_layer", sa.Boolean(), nullable=True),
        sa.Column("needs_ocr", sa.Boolean(), nullable=True),
        sa.Column("extracted_chars", sa.BigInteger(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("original_bucket", sa.Text(), nullable=True),
        sa.Column("original_object_key", sa.Text(), nullable=True),
        sa.Column("ocr_languages_used", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("email_message_id", sa.Text(), nullable=True),
        sa.Column("email_thread_id", sa.Text(), nullable=True),
        sa.Column("email_parent_doc_id", sa.UUID(), nullable=True),
        sa.Column("email_from_address", sa.Text(), nullable=True),
        sa.Column("email_from_name", sa.Text(), nullable=True),
        sa.Column("email_to_addresses", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("email_cc_addresses", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("email_date_sent", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_label_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["email_parent_doc_id"], ["documents.doc_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["topic_id"], ["corpus_topics.topic_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_table(
        "imap_command_log",
        sa.Column("log_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("label_path", sa.Text(), nullable=True),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("args_redacted", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Text(), nullable=False),
        sa.Column("response_bytes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duration_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["mail_accounts.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_table(
        "oauth_codes",
        sa.Column("code_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("code_challenge", sa.Text(), nullable=False),
        sa.Column("code_challenge_method", sa.Text(), server_default="S256", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["oauth_clients.client_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("code_id"),
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("token_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("access_token_hash", sa.Text(), nullable=False),
        sa.Column("refresh_token_hash", sa.Text(), nullable=True),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["oauth_clients.client_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("token_id"),
    )
    op.create_table(
        "upload_sessions",
        sa.Column("session_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("auto_confirm", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("total_files", sa.Integer(), server_default="0", nullable=False),
        sa.Column("uploaded", sa.Integer(), server_default="0", nullable=False),
        sa.Column("confirmed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "watched_labels",
        sa.Column("label_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("label_path", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("uidvalidity", sa.BigInteger(), nullable=True),
        sa.Column("last_uid_seen", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["mail_accounts.account_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("label_id"),
        sa.UniqueConstraint("account_id", "label_path", name="uq_watched_labels_account_path"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("message_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), server_default="", nullable=False),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tool_call_id", sa.String(length=100), nullable=True),
        sa.Column("rag_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("model_id", sa.String(length=50), nullable=True),
        sa.Column("context_pct", sa.SmallInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.conversation_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("chunk_num", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), server_default="english", nullable=False),
        sa.Column("ocr_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column(
            "fts_en",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(chunk_text, ''))", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "fts_fr",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('french', coalesce(chunk_text, ''))", persisted=True),
            nullable=True,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chunk_id"),
        sa.UniqueConstraint("doc_id", "chunk_num", name="uq_chunks_doc_num"),
    )
    op.create_table(
        "document_headings",
        sa.Column("heading_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("page_num", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("heading_id"),
    )
    op.create_table(
        "document_pages",
        sa.Column("page_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("page_num", sa.Integer(), nullable=False),
        sa.Column("page_text", sa.Text(), server_default="", nullable=False),
        sa.Column("ocr_used", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column("char_count", sa.Integer(), sa.Computed("char_length(page_text)", persisted=True), nullable=True),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("page_id"),
        sa.UniqueConstraint("doc_id", "page_num", name="uq_pages_doc_page"),
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("job_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum("extract", "ocr", "chunk", "entities", "embed", "summarize", "finalize", name="job_stage"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "error", name="job_status"),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("progress_current", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("progress_total", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("priority", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("doc_id", "stage", name="uq_jobs_doc_stage"),
    )
    op.create_table(
        "research_state",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("strategy", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("current_round", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_rounds", sa.Integer(), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("depth", sa.String(length=10), nullable=True),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.conversation_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_table(
        "uploads",
        sa.Column("upload_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.Enum("web", "watch_folder", name="upload_source"), server_default="web", nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.LargeBinary(), nullable=True),
        sa.Column("minio_bucket", sa.Text(), nullable=False),
        sa.Column("minio_object_key", sa.Text(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.doc_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["upload_sessions.session_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("upload_id"),
    )
    op.create_table(
        "watched_files",
        sa.Column("file_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("bookmark_data", sa.LargeBinary(), nullable=False),
        sa.Column("sha256", sa.LargeBinary(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.Enum("active", "removed", name="watched_file_status"), server_default="active", nullable=False
        ),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.doc_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["folder_id"], ["watched_folders.folder_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_table(
        "watched_messages",
        sa.Column("message_pk", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("label_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("imap_uid", sa.BigInteger(), nullable=False),
        sa.Column("eml_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("email_doc_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("unlabeled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["email_doc_id"], ["documents.doc_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["label_id"], ["watched_labels.label_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_pk"),
        sa.UniqueConstraint("label_id", "message_id", name="uq_watched_messages_label_message"),
    )
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("entity_text", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=False),
        sa.Column("end_char", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.chunk_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.doc_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    # Schema corrections autogenerate cannot derive from the models:
    # the users.email model field is declared as Text but production has
    # always been citext (case-insensitive), and watched_files' identity
    # uniqueness on (folder_id, relative_path) is created by raw SQL in the
    # pre-rebase chain, not declared on the model. Both are pre-existing
    # model/DB drift; see pr_followups for the model-side fixes.
    op.execute("ALTER TABLE users ALTER COLUMN email TYPE citext")
    op.execute(
        "ALTER TABLE watched_files ADD CONSTRAINT uq_watched_files_folder_path UNIQUE (folder_id, relative_path)"
    )
    op.execute("CREATE INDEX api_keys_active_idx ON public.api_keys USING btree (is_active)")
    op.execute("CREATE INDEX audit_created_idx ON public.audit_log USING btree (created_at DESC)")
    op.execute(
        "CREATE INDEX chunks_doc_embedding_idx ON public.chunks USING btree (doc_id) WHERE (embedding IS NOT NULL)"
    )
    op.execute("CREATE INDEX chunks_doc_idx ON public.chunks USING btree (doc_id)")
    op.execute(
        "CREATE INDEX chunks_embedding_hnsw_idx ON public.chunks USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64')"
    )
    op.execute("CREATE INDEX chunks_fts_en_idx ON public.chunks USING gin (fts_en)")
    op.execute("CREATE INDEX chunks_fts_fr_idx ON public.chunks USING gin (fts_fr)")
    op.execute("CREATE INDEX chunks_language_idx ON public.chunks USING btree (language)")
    op.execute("CREATE INDEX documents_status_updated_idx ON public.documents USING btree (status, updated_at DESC)")
    op.execute("CREATE INDEX documents_updated_idx ON public.documents USING btree (updated_at DESC)")
    op.execute("CREATE INDEX idx_messages_conv ON public.chat_messages USING btree (conversation_id, created_at)")
    op.execute("CREATE INDEX ix_api_request_log_created ON public.api_request_log USING btree (created_at)")
    op.execute("CREATE INDEX ix_api_request_log_endpoint ON public.api_request_log USING btree (endpoint)")
    op.execute(
        "CREATE INDEX ix_api_request_log_key_time_ep ON public.api_request_log USING btree (api_key_id, created_at DESC, endpoint)"
    )
    op.execute("CREATE INDEX ix_conversations_user_updated ON public.conversations USING btree (user_id, updated_at)")
    op.execute(
        "CREATE INDEX ix_documents_email_message_id ON public.documents USING btree (email_message_id) WHERE (email_message_id IS NOT NULL)"
    )
    op.execute(
        "CREATE INDEX ix_documents_email_parent ON public.documents USING btree (email_parent_doc_id) WHERE (email_parent_doc_id IS NOT NULL)"
    )
    op.execute(
        "CREATE INDEX ix_documents_email_thread_id ON public.documents USING btree (email_thread_id) WHERE (email_thread_id IS NOT NULL)"
    )
    op.execute("CREATE INDEX ix_entities_chunk_id ON public.entities USING btree (chunk_id)")
    op.execute("CREATE INDEX ix_entities_doc_id ON public.entities USING btree (doc_id)")
    op.execute("CREATE INDEX ix_entities_text_chunk ON public.entities USING btree (entity_text, chunk_id)")
    op.execute("CREATE INDEX ix_entities_text_trgm ON public.entities USING gin (entity_text public.gin_trgm_ops)")
    op.execute("CREATE INDEX ix_entities_type_text ON public.entities USING btree (entity_type, entity_text)")
    op.execute(
        "CREATE INDEX ix_imap_command_log_account_time ON public.imap_command_log USING btree (account_id, created_at DESC)"
    )
    op.execute("CREATE INDEX ix_imap_command_log_created ON public.imap_command_log USING btree (created_at)")
    op.execute(
        "CREATE INDEX ix_ingestion_jobs_priority_created ON public.ingestion_jobs USING btree (priority, created_at)"
    )
    op.execute("CREATE INDEX ix_oauth_codes_code_hash ON public.oauth_codes USING btree (code_hash)")
    op.execute("CREATE INDEX ix_oauth_tokens_access_hash ON public.oauth_tokens USING btree (access_token_hash)")
    op.execute("CREATE INDEX ix_oauth_tokens_refresh_hash ON public.oauth_tokens USING btree (refresh_token_hash)")
    op.execute(
        "CREATE UNIQUE INDEX ix_research_state_one_running ON public.research_state USING btree (status) WHERE ((status)::text = 'running'::text)"
    )
    op.execute("CREATE INDEX ix_uploads_session_id ON public.uploads USING btree (session_id)")
    op.execute("CREATE INDEX ix_watched_files_folder_id ON public.watched_files USING btree (folder_id)")
    op.execute("CREATE INDEX ix_watched_files_status ON public.watched_files USING btree (status)")
    op.execute("CREATE INDEX ix_watched_messages_eml_sha ON public.watched_messages USING btree (eml_sha256)")
    op.execute(
        "CREATE INDEX ix_watched_messages_label_status ON public.watched_messages USING btree (label_id, status)"
    )
    op.execute("CREATE INDEX jobs_status_idx ON public.ingestion_jobs USING btree (status)")
    op.execute("CREATE INDEX uploads_created_idx ON public.uploads USING btree (created_at DESC)")

    # Sentinel rows — verified at boot by verify_schema_sentinel().
    op.execute(
        """
        INSERT INTO schema_metadata (key, value) VALUES
            ('embed_model', 'granite-embedding-311m-multilingual-r2'),
            ('embed_dim', '768'),
            ('reranker', 'bge-reranker-v2-m3')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("embedding-v2 initial migration is not reversible; restore from backup.")
